name: APK Merger Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y unzip openjdk-17-jdk

    - name: Download AMT
      run: |
        wget https://github.com/Foellix/AMT/releases/download/v2.0.0/AMT.zip
        unzip AMT.zip -d AMT

    - name: Verify amt.properties file
      run: |
        cat AMT/AMT/amt.properties

    - name: Copy APKs to AMT
      run: |
        mkdir -p AMT/AMT/apks
        cp -r ./apk/*.apk AMT/AMT/apks/

    - name: Debug working directory
      run: |
        ls -l AMT/AMT
        ls -l

    - name: Set androidPlatforms path
      run: |
        echo "androidPlatforms=/usr/lib/android-sdk/platforms" > AMT/AMT/amt.properties

    - name: Run AMT merge
      run: |
        cd AMT/AMT
        java -jar AMT-2.0.0.jar Tachiyomi_ Cocomic_1.4.38.apk Tachiyomi_ Mangahasu_1.4.17.apk

    - name: Upload merged APK
      uses: actions/upload-artifact@v3
      with:
        name: merged-apk
        path: AMT/AMT/output/merged.apk
