name: APK Merger Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 17

      - name: Download AMT
        run: |
          wget https://github.com/FoelliX/AMT/releases/download/2.0.0/AMT_2_0_0.zip
          unzip AMT_2_0_0.zip

      - name: Create APKs directory
        run: mkdir -p AMT/AMT/apks/

      - name: Copy APK files
        run: cp -r ./apk/*.apk AMT/AMT/apks/

      - name: Setup Android SDK path
        run: echo "androidPlatforms=/usr/lib/android-sdk/platforms" > AMT/AMT/amt.properties

      - name: Run AMT merging
        run: java -jar AMT/AMT/AMT-2.0.0.jar Tachiyomi_1.apk Tachiyomi_2.apk

      - name: Upload merged APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: merged-apk
          path: AMT/AMT/output/merged.apk
