name: Merge APKs

on:
  workflow_dispatch: # Manual trigger

jobs:
  merge-apks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'  # Updated Java distribution

      - name: Install dependencies (apktool, unzip, curl)
        run: |
          sudo apt update
          sudo apt install -y apktool unzip curl

      - name: Download and extract AMT zip
        run: |
          curl -L -o AMT.zip https://github.com/FoelliX/AMT/releases/download/2.0.0/AMT_2_0_0.zip
          unzip AMT.zip -d AMT

      - name: Copy APK files from apk folder
        run: |
          mkdir apks
          cp ./apk/*.apk ./apks/

      - name: Merge APKs
        run: |
          cd AMT
          java -jar ./AMT_2_0_0/amt.jar --apks ../apks/*.apk --output ../merged.apk

      - name: Upload merged APK
        uses: actions/upload-artifact@v3
        with:
          name: merged-apk
          path: merged.apk
