name: APK Merging Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Java 17 (Zulu)
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: '17'

    - name: Download AMT
      run: |
        curl -L https://github.com/FoelliX/AMT/releases/download/2.0.0/AMT_2_0_0.zip -o AMT.zip
        unzip AMT.zip -d AMT
        ls -l AMT/AMT

    - name: Copy APK files
      run: |
        mkdir -p AMT/AMT/apks
        cp -r ./apk/*.apk AMT/AMT/apks/
        ls -l AMT/AMT/apks/

    - name: Set up amt.properties
      run: |
        echo "androidPlatforms=/usr/lib/android-sdk/platforms" > AMT/AMT/amt.properties
        cat AMT/AMT/amt.properties

    - name: Run AMT
      run: |
        java -jar AMT/AMT/AMT-2.0.0.jar A.apk B.apk
        ls -l AMT/AMT/output/
      
    - name: Upload merged APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: merged-apk
        path: AMT/AMT/output/merged.apk
