name: APK Merger Workflow

on:
  push:
    branches:
      - main

jobs:
  merge_apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y wget unzip openjdk-17-jdk apktool

    - name: Download AMT tool
      run: |
        wget https://github.com/FoelliX/AMT/releases/download/2.0.0/AMT_2_0_0.zip
        unzip AMT_2_0_0.zip -d AMT

    - name: Configure AMT
      run: |
        echo "androidPlatforms=/path/to/Android/sdks/platforms" > AMT/AMT/amt.properties
        echo "apktoolPath=/usr/bin/apktool" >> AMT/AMT/amt.properties
        echo "apktoolJar=apktool_2.6.0.jar" >> AMT/AMT/amt.properties
        echo "outputFolder=output" >> AMT/AMT/amt.properties

    - name: Copy APKs
      run: |
        mkdir -p AMT/AMT/apks
        cp apk/*.apk AMT/AMT/apks/

    - name: Run AMT tool
      run: |
        cd AMT/AMT
        java -jar AMT-2.0.0.jar A.apk B.apk

    - name: Upload the merged APK
      uses: actions/upload-artifact@v3
      with:
        name: merged-apk
        path: AMT/AMT/output/merged.apk
