name: Apk Merger Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Java 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'openjdk'

    - name: Download and extract AMT tool
      run: |
        wget https://github.com/FoelliX/AMT/releases/download/2.0.0/AMT_2_0_0.zip
        unzip AMT_2_0_0.zip -d AMT

    - name: Configure AMT
      run: |
        echo "androidPlatforms=/path/to/Android/sdks/platforms" > AMT/AMT/amt.properties

    - name: Copy APK files to the working directory
      run: |
        mkdir -p AMT/AMT/apks
        cp ./apk/*.apk AMT/AMT/apks/

    - name: Run the APK merging tool
      run: |
        cd AMT/AMT
        java -jar AMT-2.0.0.jar -d verbose ./apks/*.apk

    - name: Upload merged APK
      uses: actions/upload-artifact@v3
      with:
        name: merged-apk
        path: AMT/AMT/output/merged.apk
