name: Apk Merging Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: '17'

    - name: Download AMT zip
      run: |
        curl -L https://github.com/FoelliX/AMT/releases/download/2.0.0/AMT_2_0_0.zip -o AMT.zip
        unzip AMT.zip -d AMT/

    - name: Set up properties file
      run: echo "androidPlatforms=/path/to/Android/sdks/platforms" > AMT/AMT/amt.properties

    - name: Copy APK files to AMT directory
      run: cp -r ./apk/*.apk AMT/AMT/apks/

    - name: Check directory contents
      run: ls -al AMT/AMT/apks/

    - name: Run AMT merge
      run: java -jar AMT/AMT/AMT-2.0.0.jar -d verbose -cfg AMT/AMT/amt.properties ./AMT/AMT/apks/*.apk

    - name: Upload merged APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: merged-apk
        path: AMT/AMT/output/merged.apk
