name: Merge APKs

on:
  workflow_dispatch: # Manual trigger

jobs:
  merge-apks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies (apktool, unzip, curl)
        run: |
          sudo apt update
          sudo apt install -y apktool unzip curl

      - name: Download and extract AMT zip
        run: |
          curl -L -o AMT.zip https://github.com/FoelliX/AMT/releases/download/2.0.0/AMT_2_0_0.zip
          unzip AMT.zip -d AMT
          
      - name: Create amt.properties file
        run: |
          echo "androidPlatforms=/path/to/Android/sdks/platforms" > AMT/AMT/amt.properties
          echo "apktoolPath=/path/to/apktool" >> AMT/AMT/amt.properties
          echo "apktoolJar=apktool_2.6.0.jar" >> AMT/AMT/amt.properties
          echo "outputFolder=output" >> AMT/AMT/amt.properties
          echo "defaultExcludes=android.support.*, com.google.*, androidx.*, kotlin.*" >> AMT/AMT/amt.properties

      - name: Copy APK files to the working directory
        run: |
          mkdir -p AMT/AMT/apks
          cp ./apk/* AMT/AMT/apks/

      - name: Merge APKs
        run: |
          cd AMT/AMT
          java -jar AMT-2.0.0.jar --apks ./apks/*.apk --output ./output/merged.apk

      - name: Upload merged APK
        uses: actions/upload-artifact@v3
        with:
          name: merged-apk
          path: AMT/AMT/output/merged.apk
