name: Apk Merger

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  merge_apks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Download AMT ZIP
        run: |
          curl -L -o AMT.zip https://github.com/FoelliX/AMT/releases/download/2.0.0/AMT_2_0_0.zip
          unzip AMT.zip -d AMT

      - name: Create apks directory
        run: mkdir -p AMT/AMT/apks

      - name: Copy APK files to AMT directory
        run: cp -r ./apk/*.apk AMT/AMT/apks/

      - name: Check if APKs are in place
        run: |
          ls -l AMT/AMT/apks/

      - name: Modify amt.properties file
        run: |
          echo "androidPlatforms=/path/to/Android/sdks/platforms" > AMT/AMT/amt.properties
          cat AMT/AMT/amt.properties

      - name: Run AMT
        run: |
          cd AMT/AMT
          java -jar AMT-2.0.0.jar -check -d verbose

      - name: Upload merged APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: merged-apk
          path: AMT/AMT/output/merged.apk
